### ISSUE TITLE
have a method can transfer body ( ews getitem/exportitem) to pst file?

### ISSUE THREAD

**Issue by ABetterCat** [mooijtech/go-pst#10]
have a method can transfer body ( ews get item) to pst file?

**Comment by mooijtech** [comment]
I don't understand your question.
You can get the message body like this (from the example):
```go
for _, message := range messages {
	body, err := message.GetBody(&pstFile, formatType, encryptionType)

	if err != nil {
		fmt.Printf("Failed to get message body: %s", err)
		continue
	}

	fmt.Printf("Message body: %s", body)
}
```
Or the GetBodyHTML method.

**Comment by ABetterCat** [comment]
I want to write a pst file.EWS has the method 'export item'.I want to write a pst file from the body of export item.Is there a method?

**Comment by mooijtech** [comment]
This library is only for *reading* PST files, not creating PST files.

I haven't heard of [EWS](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getitem-operation) until now but I can see what you are referring to.

I do not know of a method to create a PST file from a GetItem operation from EWS.

EWS also doesn't support exporting email to a PST because the PST file is an Office file format so in the case 
where you do manage to mount the database on Exchange then use https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2007/bb266964(v=exchg.80)?redirectedfrom=MSDN or 
just connect via Outlook and export the Mailbox.

If you want to export (CreateItem operation) this is should be possible in combination with go-pst, as it's just XML, this library seems to do it: 
https://github.com/mhewedy/ews
https://github.com/mhewedy/ews/blob/master/create_item_test.go

**Comment by ABetterCat** [comment]
Yes,shell can do it.I have got an idea.I am trying to do it by using windows COM to call method of outlook.Thankyou very much.

**Comment by mooijtech** [comment]
No problem, good luck!
