### ISSUE TITLE
mail format 

### ISSUE THREAD

**Issue by bphd** [mooijtech/go-pst#19]
Do you know what format use Microsoft to store its mails in OST/PST files? HTML/EML/MESSAGE/etc.

**Comment by mooijtech** [comment]
Hello,

The body of a message can be in RTF, HTML or Plaintext.

Every message in a PST file contains a property context (fancy name for a table).
Each property ID references a value which is stored in bytes.

Feel free to let me know if you have any other questions.

Kind regards,
Marten Mooij


________________________________
From: xqyz ***@***.***>
Sent: Tuesday, July 5, 2022, 4:41 PM
To: mooijtech/go-pst ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mooijtech/go-pst] mail format  (Issue #19)


Do you know what format use Microsoft to store its mails in OST/PST files? HTML/EML/MESSAGE/etc.

**Comment by mooijtech** [comment]
You are correct.

I believe the PST file format was intended to preserve messages but for your use case, such as text search, this is not ideal.

Because you want text search I would recommend importing the PST file messages via go-pst into Elasticsearch.

Here you can query everything you want.

You can do a dedupe by searching for the message ID from the message header (note there is also a separate property which contains just this value, so I would add it as a separate keyword field in Elasticsearch).

For integration into other software it depends on the software. You can export the PST file messages to EML, for which I've written https://github.com/mooijtech/go-pst-export and import it to the software if it supports it. Another option is you can expose an OpenAPI specification implementation in front of Elasticsearch and make the software communicate with your API.

Please keep in mind that I have only tested go-pst on PST files. The OST file format is basically the same but has some internal differences that I have not tested and have no special logic for.

Feel free to let me know if you have any other questions.

Kind regards,
Marten Mooij

________________________________

**Comment by bphd** [comment]
`go-pst` convert it to what file for it to be supported by Elastic Search?
I'm personally more of the old school, like having file in folder, searching through them with the OS file search, or maybe `grep`, and performing different things in line command. That's why I'd like to have readable files for me to manipulate it. But my real priority is to conserve most of data out of OST, as long as the result is something else than that unusable compressed RTF files
I never used ES, I don't even know how it works. It's a specific interface? It integrates to something else? I see it running in my work computer, it's used by someone else or its meant for me and I just never used it?
Nice advice to search by message ID. But when I get two dupes, what I'm I supposed to delete? Are those files? Database entries? Folders of contents?
Exposing an API and make it communicate doesn't imply coding? Because I'm more of a scripting guy, and I'm used to search through `find` and `grep`
I head that OST is PST with some more information, that its more than just mails, it's a whole copy of the account. I know theres converters over here but its really blurry, difficult to perfectly understand all taht

**Comment by mooijtech** [comment]
Closed due to inactivity.
