### ISSUE TITLE
License Change?

### ISSUE THREAD

**Issue by korylprince** [mooijtech/go-pst#8]
Would you consider changing the License to [something here](https://pkg.go.dev/license-policy)? I would kindly suggest the MIT license.

pkg.go.dev won't even show documentation for this package since you're using WTFPL, and I imagine it's going to limit it's use in some projects. I'd love to add PST support to my own [eml2html](https://github.com/korylprince/eml2html) package.

Thanks for the work in this package and considering this request.

Edit: I noticed the badge on the README actually says MIT, but that doesn't match what's in the actual LICENSE.txt file. Maybe this is just an oversight?

**Comment by mooijtech** [comment]
Hello Koryl,

Thanks for your issue!
I originally used MIT but someone told me to use WTFPL because it was more free but I see pkg.go.dev doesn't like this license, so I've changed it.

Let me know if you have any further questions or concerns.

eml2html looks awesome, I am working on forensic software (SaaS) to present and analyze digital evidence to be presented in court so I might add your package to add functionality for exporting to HTML (I only support PST files for now).

I appreciate your feedback,
Marten Mooij

**Comment by korylprince** [comment]
Thanks!
